### ISSUE TITLE
光影猫

### ISSUE THREAD

**Issue by ghost** [Kisoul/Actions-OpenWrt-lede#1]
求一个人光影猫ldae的源码配置文集我也是找问题过来的不知你有没

**Comment by Kisoul** [comment]
> 求一个人光影猫ldae的源码配置文集我也是找问题过来的不知你有没

我有光影猫，但是我之前编译的没有bin启动不起来

**Comment by ghost** [comment]
我现在编译了一个天灵的5.15、你刚好有能直接下载你去测试下嘛，链接是现在我刚编译出来两小时前的https://github.com/Namia-A/OpenWrt-X/releases


我准备买它但是我找了一天那固件更新太慢了。
